app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('movie/<str:pk>/', views.movie, name='movie'), #to view the selected movie details
    path('add-to-list', views.add_to_list, name='add-to-list'),
    path('my-list', views.my_list, name='my-list'),
    path('search', views.search, name='search'),
    path('genre/<str:pk>/', views.genre, name='genre'),
]

netflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),  # Include blog app's URL configuration
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Serve media files

app/models.py
from django.db import models
import uuid
from django.conf import settings

# Create your models here.

class Movie(models.Model):
    GENRE_CHOICES = [
        ('action', 'Action'),
        ('comedy', 'Comedy'),
        ('drama', 'Drama'),
        ('fantacy', 'Fantacy'),
        ('horror', 'Horror'),
        ('romance', 'Romance'),
        ('scifi', 'Scifi')
    ]

    uu_id = models.UUIDField(default = uuid.uuid4)
    title = models.CharField(max_length=255)
    description = models.TextField()
    release_date = models.DateField()
    genre = models.CharField(max_length=100, choices=GENRE_CHOICES)
    length = models.PositiveIntegerField()
    image_card = models.ImageField(upload_to="movie_images/")
    image_cover = models.ImageField(upload_to="movie_images/")
    video = models.FileField(upload_to='movie_videos/')
    movie_views = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    


class MovieList(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, auth
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.conf import settings
from . models import Movie, MovieList
import re

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    featured_movie = movies[len(movies)-1]
    
    context = {
        'movies': movies,
        'featured_movie': featured_movie,  # Add this line
    }
    
    return render(request, 'index.html', context, )



@login_required  # you can also use this as >> @login_required(login_url='login')  if you did not specify login url in settings.py
def movie(request, pk):
    movie = Movie.objects.get(uu_id=pk)

    if not movie:
        return redirect('/')
    
    context = {
       'movie_details': movie,
    }
    return render(request,'movie.html', context)



# @login_required
# def my_list(request):
#     pass



@login_required
def add_to_list(request):
    if request.method == 'POST':
        movie_url_id = request.POST['movie_uuid']

        uuid_pattern = r"[-0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        match = re.search(uuid_pattern, movie_url_id)
        movie_uuid = match.group() if match else None

        # quickly search for uuid in db esle return 404
        movie = get_object_or_404(Movie, uu_id=movie_uuid)
        movie_url_list, created = MovieList.objects.get_or_create(owner = request.user, movie=movie)

        if created:
            messages.success(request, 'Movie added to your list')
            response = {
                "code": 200,
                "status": "success",
                "message": "Movie added successfully",
                "movie": created
            }
        else:
            response = {
                "code": 400,
                "status": "failed",
                "message": "Movie already in your list",
                "movie": []
            }
            messages.info(request, 'Movie already in your list')

        return JsonResponse(response)   
    
    output = {
        "code": 400,
        "status": "failed",
        "message": "Only POST requests are allowed",
        "movie": []
    }    
    return JsonResponse(output) 




@login_required(login_url="login")
def my_list(request):

    movies = MovieList.objects.filter(owner = request.user)
    user_movie_list = []
    
    for movie in movies:
        # user_movie_list.append({
        #     "id": movie.id,
        #     "movie": movie.movie.title,
        #     "uu_id": movie.movie.uu_id
        # })
        user_movie_list.append(movie.movie) #this is simple to use this way
    context = {
        "movies": user_movie_list
    }

    return render(request, 'my_list.html', context)




@login_required(login_url="login")
def search(request):
    if request.method == 'POST':
        search_query = request.POST['search']
        movies = Movie.objects.filter(title__icontains=search_query)
        context = {
            'search_term': search_query,
            'movies': movies
        }
        return render(request,'search.html', context)
    
    return redirect('/')





@login_required 
def genre(request, pk):
    movies = Movie.objects.filter(genre=pk)

    if not movie:
        return redirect('/')
    
    context = {
       'movies': movies,
       'genre': pk,
    }
    return render(request,'genre.html', context)





def user_signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']
        
        if password == password_confirmation:
            try :
                if User.objects.filter(email = email).exists():
                    messages.info(request, 'Email already exists')
                    return redirect('signup')
                elif User.objects.filter(username = username).exists():
                    messages.info(request, 'Username already exists')
                    # error_message = 'Username already exists'
                    return redirect('signup')
                
                user = User.objects.create_user(username, email, password)
                user.save()
                
                # login(request, user)

                messages.success(request, 'Registration successful. You can login now.')
                # return redirect('/', user)'Error occurred while registering user'
                return redirect('signup')
            except Exception as e:
                print(f'Error occurred while registering user: {e}')

                messages.info(request, e)
                return redirect('signup')
        
        messages.info(request, 'The passwords you entered does not match')
        # error_message = 'The passwords you entered does not match'
        return redirect('signup')
    return render(request, 'signup.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = auth.authenticate(username = username, password = password)
        #user = authenticate(username = username, password = password)# use only if you imported authentication, login, logout = from django.contrib.auth import authenticate, login, logout
        if user is not None:
            auth.login(request, user)
            # login(request, user) # use only if you imported authentication, login, logout = from django.contrib.auth import authenticate, login, logout
            messages.success(request, 'Login successful')
            return redirect('/', user)
        else:
            # error_message = 'Username or password is incorrect'
            messages.info(request, 'Username or password is incorrect')
            return redirect('login')
        
    return render(request, 'login.html')


@login_required
def user_logout(request):
    #logout(request) all works since we imported logout directly
    auth.logout(request)
    messages.success(request, 'You have been logged out')
    return redirect('login')

templates/genre.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   
    
    <!-- https://www.cdnpkg.com/toastr.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
    <!-- toastify.min.css for notification -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

    <!-- toastify.min.css for notification -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    
</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        
        
        <nav class="flex space-x-5">
            <span><a href="/">Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer">Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    <ul><a href="/genre/action/">Action</a></ul>
                    <ul><a href="/genre/comedy/">Comedy</a></ul>
                    <ul><a href="/genre/drama/">Drama</a></ul>
                    <ul><a href="/genre/horror/">Horror</a></ul>
                    <ul><a href="/genre/romance/">Romance</a></ul>
                    <ul><a href="/genre/scifi/">Science Fiction</a></ul>
                    <ul><a href="/genre/fantasy/">Fantasy</a></ul>
                </div>
            </div>

            <span><a href="/my-list">My List</a></span>
        </nav>


        <div class="flex space-x-5 items-center">
            <form action="/search" method="POST" id="search">
                {% csrf_token %}
                <input type="search" name="search" placeholder="Search" class="bg-gray-700 p-2 rounded">
                <button class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                <a href="#" class="block p-2">Welcome, {{user.username}}</a>
                <a href="/logout" class="block p-2">Logout</a>
            </div>
        </div>
    </header>
    
    <hr>

    <section class="py-10 px-5">
    
        <div align="center">
            <h2 class="text-xl mb-5">
                '{{genre | title}}' Films
            </h2>
        </div>
        <div class="flex space-x-5 overflow-x-auto">

            {% for movie in movies %}
            <div class="w-40 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center;">
            </div>
            {% endfor %}
    </section>
    
   

    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img width="1000" height="100" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="movie.html">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                <button id="addToListButton" onclick="addItemToList()" class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <!--- toastify-js for notification  -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="https://myeventsgh.com/vendor/sweetalert/sweetalert.all.js" nonce="rAnd0m"></script>

    <script src="{% static 'assets/js/custom.js' %}" type="text/javascript"></script>
    
</body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" />


    <!-- https://www.cdnpkg.com/toastr.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
    <!-- toastify.min.css for notification -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

    <!-- toastify.min.css for notification -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    
   
</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        
        
        <nav class="flex space-x-5">
            <span><a href="/">Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer">Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    <ul><a href="/genre/action/">Action</a></ul>
                    <ul><a href="/genre/comedy/">Comedy</a></ul>
                    <ul><a href="/genre/drama/">Drama</a></ul>
                    <ul><a href="/genre/horror/">Horror</a></ul>
                    <ul><a href="/genre/romance/">Romance</a></ul>
                    <ul><a href="/genre/scifi/">Science Fiction</a></ul>
                    <ul><a href="/genre/fantasy/">Fantasy</a></ul>
                </div>
            </div>

            <span><a href="/my-list">My List</a></span>
        </nav>


        <div class="flex space-x-5 items-center">
            <form action="search" method="POST" id="search">
                {% csrf_token %}
                <input type="/search" name="search" placeholder="Search" class="bg-gray-700 p-2 rounded" required>
                <button class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                <a href="#" class="block p-2">Welcome, {{user.username}}</a>
                <a href="/logout" class="block p-2">Logout</a>
            </div>
        </div>
    </header>
    <section class="relative py-20 px-10" style="background-image: url('{{featured_movie.image_cover.url}}'); background-size: cover; background-position: center;">
        <div>
            <div  class="mb-5 text-3xl" style="border: 0p; border-radius: 5px; padding: 6px; opacity: 0.5; background-color: #374151;">
                <h1 style="color: rgb(252, 5, 5);border: 0p; border-radius: 5px; padding: 6px;" class="text-5xl mb-5"><b>{{featured_movie.title}}</b></h1>
                <p style="color: rgb(252, 249, 249);" class="mb-5">{{featured_movie.description}}</p>
            </div>
            
            <div class="flex space-x-4">
                <a href="/movie/{{featured_movie.uu_id}}">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
            </div>
        </div>
    </section>
    <section class="py-10 px-5">
    
        <h2 class="text-xl mb-5">Popular on Netflix</h2>
        <div class="flex space-x-5 overflow-x-auto" style="max-width: 100%;">

            {% for movie in movies %}
            <div class="w-40 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center; max-width: 100%;">
            </div>
            {% endfor %}
    </section>
    
    

    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img width="1000" height="100" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="movie.html">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>

                <button id="addToListbtn" onclick="addItemToList()" class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
            
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <!--- toastify-js for notification  -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="https://myeventsgh.com/vendor/sweetalert/sweetalert.all.js" nonce="rAnd0m"></script>


    <script src="{% static 'assets/js/custom.js' %}" type="text/javascript"></script>

</body>

</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/auth.css' %}" />

    <title>Netflix | Login</title>
</head>
<body>

    <div class="bg-image">
        <div class="signup-container">
            <h1 class="text-center">Login</h1>
            <hr>
            <h2  style="margin: 15px;">Unlimited movies, TV shows, and more.</h2>

            <div>
                {% if error_message %}
                    <div align="center" style="color: red;">
                        <h2>
                            {{ error_message }}
                        </h2>
                    </div>
                {% elif messages %}    
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-warning text-center text-danger">
                            <small>{{ message }}</small>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>


            <form action="" method="POST">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Username" required/>
                <input type="password" name="password" placeholder="Password" required/>
                <button style="color:white" type="submit" class="signup-btn">Login</button>
            </form>
            <div class="help-text" align="center">
                <span>Ready to watch? Enter your email to login into your membership account.</span>
                <br>
                <br>
                <span>Dont have an account? | <a href="/signup">Signup Here</a></span>
            </div>
        </div>
    </div>

</body>
</html>

templates/my_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movies</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   

    
    <!-- https://www.cdnpkg.com/toastr.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
    <!-- toastify.min.css for notification -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

    <!-- toastify.min.css for notification -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    
</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        
        
        <nav class="flex space-x-5">
            <span><a href="/">Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer">Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    <ul><a href="/genre/action/">Action</a></ul>
                    <ul><a href="/genre/comedy/">Comedy</a></ul>
                    <ul><a href="/genre/drama/">Drama</a></ul>
                    <ul><a href="/genre/horror/">Horror</a></ul>
                    <ul><a href="/genre/romance/">Romance</a></ul>
                    <ul><a href="/genre/scifi/">Science Fiction</a></ul>
                    <ul><a href="/genre/fantasy/">Fantasy</a></ul>
                </div>
            </div>

            <span><a href="/my-list">My List</a></span>
        </nav>


        <div class="flex space-x-5 items-center">
            <form action="search" method="POST" id="search" id="search">
                {% csrf_token %}
                <input type="/search" name="search" placeholder="Search" class="bg-gray-700 p-2 rounded" required>
                <button class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                <a href="#" class="block p-2">Welcome, {{user.username}}</a>
                <a href="/logout" class="block p-2">Logout</a>
            </div>
        </div>
    </header>
    
    <hr>

    <section class="py-10 px-5">
    
        <div align="center">
            <h2 class="text-xl mb-5">
                My List
            </h2>
        </div>
        <div class="flex space-x-5 overflow-x-auto">

            {% for movie in movies reversed %}
           <div class="w-40 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center; max-width: 100%;">
            </div>
            {% endfor %}
    </section>
    
   

    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img width="1000" height="100" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="movie.html">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                <!-- <button id="addToListButton" onclick="addItemToList()" class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button> -->
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <!--- toastify-js for notification  -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="https://myeventsgh.com/vendor/sweetalert/sweetalert.all.js" nonce="rAnd0m"></script>

    <script src="{% static 'assets/js/custom.js' %}" type="text/javascript"></script>
    
</body>

</html>